# [START django_app]
runtime: python39

entrypoint: gunicorn -b :$PORT django_project.wsgi

env_variables:
  AWS_ACCESS_KEY_ID: "<YOUR_AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<YOUR_AWS_SECRET_ACCESS_KEY>"
  AWS_STORAGE_BUCKET_NAME: "YOUR_AWS_STORAGE_BUCKET_NAME"

automatic_scaling:
  target_cpu_utilization: 0.5
  target_throughput_utilization: 0.5
  max_concurrent_requests: 20
  min_instances: 1
  max_instances: 10
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
# [END django_app]
